server:
  port: 8000

jwt:
  secret: 6re465Ok7J2AIOychO2VmOyXrOyEnCDsnbTsg4HsnZgg67aZ7J6h7JWEIOyduOuPhO2VmOqyoOuLpOuKlCDsnbQg7J206rKD7J2064uk
  expiration: 864000
  refresh-token:
    expiration: 864000